import "@styles/globals.scss";

import { Raleway as Font } from "next/font/google";
const font = Font({ subsets: ["latin"] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={font.className}>
      <body>
        {children}
      </body>
    </html>
  )
}
